Ctrlflow Automated Error Reporting Client Examples
==================================================

Examples of how to use various clients to communicate with the https://www.ctrlflow.com/automated-error-reporting/[Ctrlflow Automated Error Reporting (AER) server].

At the moment, the following examples are available:

link:log4j2-java-example[Log4j 2 Java Example]::
If you are developing a stand-alone *Java application* that uses the popular https://logging.apache.org/log4j/2.x/[*Log4j 2*] logging framework, have a look at this example.
It shows you how to configure Log4j 2 to send error reports to a Ctrlflow AER server.

link:logback-java-example[Logback Java Example]::
If you are developing a stand-alone *Java application* that uses the popular https://logback.qos.ch/[*Logback*] logging framework, have a look at this example.
It shows you how to configure Logback to send error reports to a Ctrlflow AER server.

link:simple-java-example[Simple Java Example]::
If you are developing a stand-alone *Java application*  that uses none of the logging frameworks supported out-of-the-box, have a look at this example.
It shows you how to use the Ctrlflow AER Simple Client to send caught exceptions to your server.
